name = "LC3-Lean"
version = "0.1.0"
defaultTargets = ["lc3-lean"]

[[lean_lib]]
name = "LC3Lean"

[[lean_lib]]
name = "LC3Correct"
globs = ["LC3Correct", "LC3Correct.ExecutionCorrect", "LC3Correct.RegisterLemmas", "LC3Correct.MemoryLemmas"]

[[lean_exe]]
name = "lc3-lean"
root = "Main"
